services:
  web:
    build: ./web
    container_name: sniper-web
    restart: unless-stopped
    ports:
      - "4321:4321"
    networks:
      - sniper-net
    deploy:
      resources:
        limits:
          memory: 150M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ingestor:
    build: ./ingestor
    container_name: sniper-ingestor
    restart: unless-stopped
    environment:
      - ZMQ_PORT=5555
      - REDIS_HOST=redis
    ports:
      - "3000:3000"
    networks:
      - sniper-net
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  engine:
    build: ./engine
    container_name: sniper-engine
    restart: unless-stopped
    environment:
      - ZMQ_SRC_HOST=ingestor
      - ZMQ_SRC_PORT=5555
      - REDIS_HOST=redis
    networks:
      - sniper-net
    depends_on:
      - ingestor
      - redis
    deploy:
      resources:
        limits:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:alpine
    container_name: sniper-redis
    restart: unless-stopped
    # Optimizamos Redis para ahorrar RAM: sin persistencia pesada
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru --save ""
    networks:
      - sniper-net
    deploy:
      resources:
        limits:
          memory: 100M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  sniper-net:
    driver: bridge
