services:
  web:
    build: ./web
    container_name: sniper-web
    restart: unless-stopped
    ports:
      - "4321:4321"
    networks:
      - sniper-net
    depends_on:
      - ingestor

  ingestor:
    build: ./ingestor
    container_name: sniper-ingestor
    restart: unless-stopped
    environment:
      - ZMQ_PORT=5555
      - REDIS_HOST=redis
    ports:
      - "3000:3000"
    networks:
      - sniper-net
    depends_on:
      - redis

  engine:
    build: ./engine
    container_name: sniper-engine
    restart: unless-stopped
    environment:
      - ZMQ_SRC_HOST=ingestor
      - ZMQ_SRC_PORT=5555
      - REDIS_HOST=redis
    networks:
      - sniper-net
    depends_on:
      - ingestor
      - redis

  redis:
    image: redis:alpine
    container_name: sniper-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - sniper-net

networks:
  sniper-net:
    driver: bridge
